services:
  n9e:
    image: flashcatcloud/nightingale:8.0.0
    container_name: n9e
    hostname: n9e
    restart: always
    environment:
      GIN_MODE: debug
      TZ: Asia/Shanghai
    volumes:
      - ./config:/app/etc
      - ./n9e.db:/app/n9e.db
    ports:
      - "17000:17000"
    command: >
      sh -c "/app/n9e"
    depends_on:
      - vm

  vm:
    image: victoriametrics/victoria-metrics:v1.121.0
    container_name: vm
    hostname: vm
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8428:8428"
    command:
      - "--loggerTimezone=Asia/Shanghai"