---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: traefik
  namespace: traefik
  labels:
    app: traefik

spec:
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-controller
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: traefik
          image: traefik:v3.3
          ports:
            - name: web
              containerPort: 80
              hostPort: 80
            - name: dashboard
              containerPort: 8080
              hostPort: 8080
            - name: tcpep
              containerPort: 9000
              hostPort: 9000
            - name: udpep
              containerPort: 9001
              hostPort: 9001
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          args:
            - --configfile=/etc/traefik/config/traefik.yaml
          volumeMounts:
            - name: config
              mountPath: /etc/traefik/config
      volumes:
        - name: config
          configMap:
            name: traefik-config

---
apiVersion: v1
kind: Service
metadata:
  namespace: traefik
  labels:
    app: traefik
  name: traefik
spec:
  selector:
    app: traefik
  ports:
    - name: web
      port: 80
      targetPort: 80
    - name: dashboard
      port: 8080
    - name: tcpep
      protocol: TCP
      port: 9000
    - name: udpep
      protocol: UDP
      port: 9001

---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: traefik
spec:
  controllerName: traefik.io/gateway-controller
